require("keymaps")
require("lazy-config")
require("options")
require("autopairs-config")
-- require("lualine-config")
require("nvim-tree-config")
require("telescope-config")
require("toggleterm-config")
require("treesitter-config")
require("whichkey")
require("bufferline-config")
