[colors.cursor]
cursor = "#ffffff"

[colors.primary]
background = "0x1d2021"

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
#auto_scroll = false
history = 10000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = true
opacity = 0.97

[window.dimensions]
columns = 240
lines = 80

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
#import = ["/home/mvthexz/.config/alacritty/catppuccin/catppuccin-mocha.yml"]

[terminal]
